package az.gmb.taxdata.service;

import org.springframework.dao.DataAccessException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;

import java.util.Base64;
import java.util.List;

/**
 * Resolves the cloud-backup AES-256 master key from Supabase Vault.
 *
 * No operator/user supplied key is required. On the first production startup,
 * PostgreSQL generates 32 cryptographically secure random bytes using
 * pgcrypto and stores the Base64 value directly in Supabase Vault. Later
 * startups only read the same named Vault secret.
 */
@Service
public class SupabaseVaultKeyService {
    private static final String SECRET_NAME = "taxdata_cloud_backup_master_key_v1";
    private static final String SECRET_DESCRIPTION =
            "TaxData cloud workspace backup AES-256 master key. Auto-generated by PostgreSQL; do not edit manually.";

    private final JdbcTemplate jdbc;
    private volatile byte[] cachedKey;

    public SupabaseVaultKeyService(JdbcTemplate jdbc) {
        this.jdbc = jdbc;
    }

    public byte[] loadOrCreateAes256Key() {
        byte[] cached = cachedKey;
        if (cached != null) return cached.clone();

        synchronized (this) {
            if (cachedKey != null) return cachedKey.clone();

            ensureExtensions();
            String secret = readSecret();
            if (secret == null || secret.isBlank()) {
                createSecretInSupabase();
                secret = readSecret();
            }
            if (secret == null || secret.isBlank()) {
                throw new IllegalStateException("Supabase Vault master key yaradıla və ya oxuna bilmədi.");
            }

            byte[] decoded;
            try {
                decoded = Base64.getDecoder().decode(secret.trim());
            } catch (IllegalArgumentException e) {
                throw new IllegalStateException("Supabase Vault-da saxlanan cloud backup açarı Base64 formatında deyil.", e);
            }
            if (decoded.length != 32) {
                throw new IllegalStateException("Supabase Vault cloud backup açarı 32 bayt AES-256 olmalıdır.");
            }
            cachedKey = decoded;
            return decoded.clone();
        }
    }

    public String secretName() {
        return SECRET_NAME;
    }

    private void ensureExtensions() {
        // Supabase documents Vault as the `supabase_vault` extension in schema `vault`.
        jdbc.execute("CREATE EXTENSION IF NOT EXISTS supabase_vault WITH SCHEMA vault");
        // Supabase installs pgcrypto in the extensions schema; this is idempotent.
        jdbc.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions");
    }

    private String readSecret() {
        List<String> rows = jdbc.query("""
                SELECT decrypted_secret
                  FROM vault.decrypted_secrets
                 WHERE name=?
                 ORDER BY created_at DESC
                 LIMIT 1
                """, (rs, rowNum) -> rs.getString(1), SECRET_NAME);
        return rows.isEmpty() ? null : rows.get(0);
    }

    private void createSecretInSupabase() {
        try {
            // The raw random value is generated inside PostgreSQL and is passed
            // directly to Vault; no human/operator generated key is involved.
            jdbc.queryForObject("""
                    SELECT vault.create_secret(
                        encode(extensions.gen_random_bytes(32), 'base64'),
                        ?,
                        ?
                    )
                    """, Object.class, SECRET_NAME, SECRET_DESCRIPTION);
        } catch (DataAccessException first) {
            // A concurrent replica may have created the unique named secret.
            // If it now exists, this is success; otherwise surface the root cause.
            String existing = readSecret();
            if (existing == null || existing.isBlank()) throw first;
        }
    }
}
